# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XxpYEyLKcMs32H1NKyJoaJPMQR-JaQxq

1.Creating collection.
"""

client = pymongo.MongoClient("mongodb://localhost:27017")

db = client["mydb"]
mycol = db["customers"]

"""2.Inserting the record."""

data= {'name': 'Ram', 'Phone_no': 9876543210,'salary': 50000,'Place': 'Mumbai'}
mycol.insert_one(data)

"""3.Make a query to find records you just created."""

for each in mycol.find():
    print(each)

"""4.Modifying the records."""

new_data={'name': 'Ram', 'Phone_no': 9876543210,'salary': 10000,'Place': 'Chennai'}
mycol.update_one(data,{'$set': new_data})

"""
5.Deleting the record.
"""

mycol.delete_one(new_data)